### ISSUE TITLE
QND SPID Mage Pack-95050-1-1-1689017101.zip not available but is required for MGO download.

### ISSUE THREAD

**Issue by SirSaganahad** [Moyse06/MadGodsOverhaul#1]
Wabbajack install of MGO is stopped due to this file not available.  Can't find the file on Nexus or GitHub.  See no way to modify Wabbajack modlist to delete this tiny 15Kb file that is halting this huge download!  Very excited to experience MGO, so any help is appreciated.

**Comment by SirSaganahad** [comment]
Found forum on dischord, sorry.

**Comment by Moyse06** [comment]
No longer an issue.
